### ISSUE TITLE
Integrations "API Error (403): Missing access token" on develop and nightly

### ISSUE THREAD

**Issue by Twi1ightSparkle** [element-hq/element-integration-manager#116] opened 2024-03-15 15:07 UTC
### Steps to reproduce

Open a widget that requires auth on the current Element Desktop Nightly or develop.element.io

#### What did you expect?

Working widgets

#### What happened instead?

![Screenshot 2024-03-15 at 3 04 47 PM](https://github.com/element-hq/element-web/assets/19155609/41021004-19da-44b1-aabf-62293b533ea0)

### Operating system

macOS (unknown version, but probably the latest), Debian 12

### Browser information

Firefox 123.0.1

### URL for webapp

develop.element.io

### Application version

Web:

Element version: 4e492da1e496-react-3c6fd5862816-js-8e0ef5ff2cd9
Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

Desktop:

Element Nightly version: 2024031501
Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

### Homeserver

matrix.org and I'm guessing element.io?

### Will you send logs?

Yes

**Comment by Twi1ightSparkle** [comment] 2024-03-15 15:09
The same integrations are working on Element Desktop stable 1.11.59 and .61 (Olm 3.2.15) on Mac

**Comment by Twi1ightSparkle** [comment] 2024-03-15 15:40
Also possibly an issue with the Rust SDK? On app.element.io
Element version: 1.11.61
Crypto version: Rust SDK 0.7.0 (b1918e9), Vodozemac 0.5.1

I just get white where the widget should have been

![Screenshot 2024-03-15 at 3 38 58 PM](https://github.com/element-hq/element-web/assets/19155609/d8b669e3-9e43-4c53-9963-b7068c141cff)

**Comment by ara4n** [comment] 2024-03-19 17:04
bumping this to O-Frequent because some users depend heavily on widgets

**Comment by Sofatraining** [comment] 2024-03-27 12:30
Same Error on Element Desktop - Version : 1.11.62 after Update Today

**Comment by Half-Shot** [comment] 2024-03-27 15:53
Looks to be caused by https://github.com/matrix-org/matrix-react-sdk/pull/12295. In v1.11.62+ we're not appending the access token to scalar requests which is probably due to the changes to make the widget URL static in the linked PR. I'll try to get a resolution from the web team.

**Comment by Half-Shot** [comment] 2024-04-03 13:18
Fixed as of v1.11.63. Thanks team :)

**Closed as completed by Half-Shot** 2024-04-03 13:18 UTC
Labels: T-Defect, S-Major, O-Frequent

**Comment by mandulaj** [comment] 2025-01-22 14:58
Seems to have reappeard in (Riot version: 1.11.77)
But fixed in (Element version: 1.11.90)

Also similar issues in #37 #28 and #87
